import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Modal from '@/Components/Modal';
import StatusBadge from '@/Components/PurchaseInvoices/StatusBadge';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';

const money = (value, currency = 'CLP') => value == null ? '—' : new Intl.NumberFormat('es-CL', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value);
const date = (value) => value ? new Intl.DateTimeFormat('es-CL').format(new Date(`${value}T12:00:00`)) : '—';
const different = (a, b) => a != null && b != null && Number(a) !== Number(b);
const formatSize = (bytes) => bytes == null ? '' : bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes / 1024).toFixed(0)} KB` : `${(bytes / 1048576).toFixed(1)} MB`;
const isImage = (mime) => mime ? mime.startsWith('image/') : false;

export default function Show({ invoice, objectionReasons, canDecide, assignmentAccess = {}, users = [] }) {
    const [objecting, setObjecting] = useState(false);
    const [assigningResponsible, setAssigningResponsible] = useState(false);
    const [assigningPo, setAssigningPo] = useState(false);
    const [assigningSubstitute, setAssigningSubstitute] = useState(false);
    const [confirmingApproval, setConfirmingApproval] = useState(false);
    const form = useForm({ motivo_objecion_id: '', comentario_objecion: '' });
    const responsibleForm = useForm({ user_id: invoice.manual_responsible?.id || '', comment: '' });
    const poForm = useForm({ manual_oc_doc_num: invoice.manual_purchase_order?.doc_num || '', manual_oc_doc_entry: invoice.manual_purchase_order?.doc_entry || '', comment: '' });
    const substituteForm = useForm({ user_id: invoice.substitute_user?.id || '', comment: '' });
    const approvalForm = useForm({ attachments: [] });
    const groups = useMemo(() => Object.values(invoice.lines.reduce((result, line) => {
        const key = line.oc_doc_entry || 'sin-oc';
        result[key] ||= { number: line.oc_doc_num, date: line.oc_date, comments: line.oc_comments, ownerCode: line.owner_code, lines: [] };
        result[key].lines.push(line);
        return result;
    }, {})), [invoice.lines]);

    const approve = () => {
        const data = new FormData();
        approvalForm.data.attachments.forEach((file) => data.append('attachments[]', file));
        data.append('_method', 'POST');
        router.post(route('purchase-invoice-approvals.approve', invoice.id), data, { preserveScroll: true, forceFormData: true, onSuccess: () => setConfirmingApproval(false) });
    };
    const object = (event) => {
        event.preventDefault();
        form.post(route('purchase-invoice-approvals.object', invoice.id), { preserveScroll: true, onSuccess: () => setObjecting(false) });
    };

    const addAttachments = (files) => {
        const current = [...approvalForm.data.attachments];
        const newFiles = Array.from(files).filter((f) => f && !current.some((c) => c.name === f.name && c.size === f.size));
        approvalForm.setData('attachments', [...current, ...newFiles].slice(0, 5));
    };
    const removeAttachment = (index) => {
        const current = [...approvalForm.data.attachments];
        current.splice(index, 1);
        approvalForm.setData('attachments', current);
    };

    return (
        <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800">Detalle de factura</h2>}>
            <Head title={`Factura ${invoice.folio}`} />
            <div className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6">
                <Link href={route('purchase-invoice-approvals.index')} className="text-sm font-semibold text-green-700 hover:text-green-900">← Volver a facturas</Link>

                <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
                    <div className="border-b border-gray-100 bg-gradient-to-r from-green-50 to-orange-50 p-5 sm:p-7">
                        <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start">
                            <div><p className="text-sm font-semibold uppercase tracking-wider text-green-700">Factura {invoice.folio}</p><h1 className="mt-1 text-2xl font-bold text-gray-900 sm:text-3xl">{invoice.provider}</h1><p className="mt-2 text-3xl font-bold text-gray-900">{money(invoice.total, invoice.currency)}</p></div>
                            <div className="flex flex-col items-start gap-2 sm:items-end"><StatusBadge status={invoice.status} /><span className={`text-sm font-medium ${invoice.days_to_due != null && invoice.days_to_due < 0 ? 'text-red-600' : 'text-gray-600'}`}>{invoice.days_to_due == null ? 'Sin vencimiento informado' : invoice.days_to_due < 0 ? `Vencida hace ${Math.abs(invoice.days_to_due)} días` : `Vence en ${invoice.days_to_due} días`}</span></div>
                        </div>
                    </div>
                    {invoice.cancelled && <div className="border-b border-red-200 bg-red-50 px-5 py-3 text-sm font-semibold text-red-800">Documento cancelado en SAP. Se conserva para auditoría y no admite decisiones.</div>}
                    <div className="grid gap-6 p-5 sm:grid-cols-2 sm:p-7">
                        <div><h2 className="font-bold text-gray-900">Factura</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><dt className="text-gray-500">DocEntry</dt><dd>{invoice.factura_doc_entry}</dd><dt className="text-gray-500">TransId</dt><dd>{invoice.factura_trans_id || '—'}</dd><dt className="text-gray-500">Fecha factura</dt><dd>{date(invoice.invoice_date)}</dd><dt className="text-gray-500">Vencimiento</dt><dd>{date(invoice.due_date)}</dd><dt className="text-gray-500">Moneda</dt><dd>{invoice.currency}</dd><dt className="text-gray-500">Estado SAP</dt><dd>{invoice.cancelled ? 'Cancelada' : 'Vigente'}</dd></dl></div>
                        <div><h2 className="font-bold text-gray-900">Responsables</h2><div className="mt-3 space-y-2">{invoice.responsibles.length === 0 && <p className="rounded-lg bg-orange-50 px-3 py-3 text-sm font-semibold text-orange-800">Responsable SAP sin usuario asociado</p>}{invoice.responsibles.map((responsible) => <div key={responsible.owner_code} className="flex items-center justify-between rounded-lg bg-gray-50 px-3 py-2 text-sm"><span><strong>{responsible.name || 'Responsable SAP sin usuario asociado'}</strong><span className="ml-2 text-gray-400">OwnerCode {responsible.owner_code}</span></span><StatusBadge status={responsible.status} /></div>)}</div></div>
                    </div>
                </section>

                {invoice.status === 'OBJETADO' && <section className="rounded-xl border border-red-200 bg-red-50 p-5"><h2 className="font-bold text-red-900">Objeción registrada</h2><p className="mt-2 text-sm text-red-800"><strong>{invoice.objection_reason}</strong> · {invoice.objected_by}</p><p className="mt-1 whitespace-pre-wrap text-sm text-red-700">{invoice.objection_comment}</p></section>}

                {invoice.association_conflict && <section className="rounded-xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">OC detectada posteriormente en SAP</h2><p className="mt-1 text-sm text-amber-800">Existe una OC manual #{invoice.manual_purchase_order?.doc_num} y SAP ahora informa {invoice.purchase_orders.join(', ')}. Ningún dato fue sobrescrito.</p>{assignmentAccess.reconcile && <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => router.post(route('purchase-invoice-approvals.reconcile-po', invoice.id), { preferred_oc_source: 'SAP', comment: 'Se prioriza la asociación informada por SAP.' }, { preserveScroll: true })} className="rounded-lg bg-amber-800 px-4 py-2 text-sm font-semibold text-white">Usar OC de SAP</button><button onClick={() => router.post(route('purchase-invoice-approvals.reconcile-po', invoice.id), { preferred_oc_source: 'MANUAL', comment: 'Se conserva como preferente la asociación manual.' }, { preserveScroll: true })} className="rounded-lg border border-amber-400 bg-white px-4 py-2 text-sm font-semibold text-amber-900">Mantener OC manual</button></div>}</section>}

                {(assignmentAccess.responsible || assignmentAccess.purchaseOrder || assignmentAccess.substitute) && <section className="rounded-xl border border-gray-200 bg-white p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-bold text-gray-900">Gestión manual</h2><p className="mt-1 text-sm text-gray-500">La asignación manual se audita y se conserva aunque SAP reenvíe la factura.</p></div><div className="flex flex-wrap gap-2">{assignmentAccess.responsible && <button onClick={() => setAssigningResponsible(true)} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white">{invoice.manual_responsible ? 'Cambiar responsable' : 'Asignar responsable'}</button>}{assignmentAccess.substitute && <button onClick={() => setAssigningSubstitute(true)} className="rounded-lg border border-amber-300 bg-amber-50 px-4 py-2 text-sm font-semibold text-amber-800">{invoice.substitute_user ? 'Cambiar suplente' : 'Asignar suplente'}</button>}{assignmentAccess.purchaseOrder && <button onClick={() => setAssigningPo(true)} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">{invoice.manual_purchase_order ? 'Cambiar OC manual' : 'Asignar OC manual'}</button>}</div></div>{invoice.manual_responsible && <p className="mt-3 text-sm text-gray-700">Responsable manual: <strong>{invoice.manual_responsible.name}</strong>{invoice.assigned_by ? ` · asignado por ${invoice.assigned_by}` : ''}</p>}{invoice.substitute_user && <p className="mt-1 text-sm text-gray-700">Suplente: <strong>{invoice.substitute_user.name}</strong>{invoice.substitute_assigned_by ? ` · asignado por ${invoice.substitute_assigned_by}` : ''}</p>}</section>}

                <section className="space-y-4"><div><h2 className="text-xl font-bold text-gray-900">{invoice.purchase_orders.length || invoice.manual_purchase_order ? 'Órdenes asociadas' : 'Detalle de factura sin OC'}</h2><p className="text-sm text-gray-500">{invoice.purchase_orders.length ? 'Las diferencias se resaltan, pero no bloquean la aprobación.' : 'SIN OC ASOCIADA · se muestran los datos contables enviados por SAP.'}</p>{invoice.manual_purchase_order && <p className="mt-2 inline-flex rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">OC manual #{invoice.manual_purchase_order.doc_num}</p>}</div>
                    {groups.map((group, index) => <article key={`${group.number}-${index}`} className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
                        <div className="flex flex-col justify-between gap-2 border-b border-gray-100 bg-gray-50 px-5 py-4 sm:flex-row"><div><h3 className="font-bold text-gray-900">{group.number ? `OC #${group.number}` : 'SIN OC ASOCIADA'}</h3><p className="text-sm text-gray-500">{group.number ? `${date(group.date)} · OwnerCode ${group.ownerCode ?? 'sin informar'}` : 'Factura directa recibida desde SAP'}</p></div><p className="max-w-xl text-sm text-gray-600">{group.comments || (group.number ? 'Sin comentario de OC' : 'Sin datos de orden de compra')}</p></div>
                        <div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-white text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Descripción / cuenta</th><th className="px-4 py-3">Cantidad OC</th><th className="px-4 py-3">Cantidad factura</th><th className="px-4 py-3">Monto OC</th><th className="px-4 py-3">Monto factura</th></tr></thead><tbody className="divide-y divide-gray-100">{group.lines.map((line) => <tr key={line.id}><td className="px-4 py-4"><div className="font-medium text-gray-900">{line.description || line.item_code || 'Sin descripción'}</div><div className="mt-1 text-xs text-gray-500">{line.area || 'Sin área'} · {line.species || 'Sin especie'}</div>{(line.account_format_code || line.account_code || line.account_name) && <div className="mt-1 text-xs font-semibold text-blue-700">Cuenta {line.account_format_code || line.account_code} · {line.account_name || 'Sin nombre'}</div>}</td><td className={`px-4 py-4 ${different(line.oc_quantity, line.invoice_quantity) ? 'bg-amber-50 font-bold text-amber-800' : ''}`}>{line.oc_quantity ?? '—'}</td><td className={`px-4 py-4 ${different(line.oc_quantity, line.invoice_quantity) ? 'bg-amber-50 font-bold text-amber-800' : ''}`}>{line.invoice_quantity ?? '—'}</td><td className={`px-4 py-4 ${different(line.oc_total, line.invoice_total) ? 'bg-amber-50 font-bold text-amber-800' : ''}`}>{money(line.oc_total, invoice.currency)}</td><td className={`px-4 py-4 ${different(line.oc_total, line.invoice_total) ? 'bg-amber-50 font-bold text-amber-800' : ''}`}>{money(line.invoice_total, invoice.currency)}</td></tr>)}</tbody></table></div>
                        <div className="border-t border-gray-100 px-5 py-3 text-sm text-gray-600">{!group.number ? <span>Factura #{invoice.factura_doc_entry} sin OC</span> : group.lines.some((line) => line.route === 'OC_ENTRADA_FACTURA') ? <span>OC #{group.number} → Entrada #{group.lines.find((line) => line.goods_receipt_number)?.goods_receipt_number || '—'} → Factura #{invoice.factura_doc_entry}</span> : <span>Relación directa OC #{group.number} → Factura #{invoice.factura_doc_entry}</span>}</div>
                    </article>)}
                </section>

                {canDecide && <div className="sticky bottom-3 flex gap-3 rounded-xl border border-gray-200 bg-white/95 p-4 shadow-lg backdrop-blur"><button onClick={() => setConfirmingApproval(true)} className="flex-1 rounded-lg bg-green-700 px-5 py-3 font-bold text-white hover:bg-green-800">Aprobar</button><button onClick={() => setObjecting(true)} className="flex-1 rounded-lg border border-red-300 bg-white px-5 py-3 font-bold text-red-700 hover:bg-red-50">Objetar</button></div>}

                {invoice.attachments.length > 0 && <section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-bold text-gray-900">Respaldos adjuntos</h2><ul className="mt-3 divide-y divide-gray-100">{invoice.attachments.map((att) => <li key={att.id} className="flex items-center justify-between py-2 text-sm"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-lg text-xs font-bold ${isImage(att.mime_type) ? 'bg-blue-50 text-blue-700' : 'bg-gray-100 text-gray-600'}`}>{isImage(att.mime_type) ? 'IMG' : 'PDF'}</span><div><p className="font-medium text-gray-800">{att.original_name}</p><p className="text-xs text-gray-500">{formatSize(att.size)}{att.uploaded_by ? ` · ${att.uploaded_by}` : ''}</p></div></div><Link href={route('purchase-invoice-approvals.download-attachment', [invoice.id, att.id])} className="text-sm font-semibold text-green-700 hover:underline">Descargar</Link></li>)}</ul></section>}

                <section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-bold text-gray-900">Historial</h2><ol className="mt-4 space-y-3">{invoice.history.map((item) => <li key={item.id} className="border-l-2 border-green-200 pl-4 text-sm"><p className="font-semibold text-gray-800">{item.event.replaceAll('_', ' ')}</p><p className="text-gray-500">{new Date(item.created_at).toLocaleString('es-CL')} {item.user ? `· ${item.user}` : ''}</p>{item.comment && <p className="mt-1 text-gray-700">{item.comment}</p>}</li>)}</ol></section>
            </div>

            <Modal show={objecting} onClose={() => setObjecting(false)} maxWidth="lg"><form onSubmit={object} className="p-6"><h2 className="text-xl font-bold text-gray-900">Objetar factura</h2><p className="mt-1 text-sm text-gray-500">Contabilidad recibirá el motivo y tu comentario.</p><div className="mt-5 space-y-4"><div><label className="text-sm font-medium text-gray-700">Motivo</label><select value={form.data.motivo_objecion_id} onChange={(e) => form.setData('motivo_objecion_id', e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring-red-500"><option value="">Selecciona un motivo</option>{objectionReasons.map((reason) => <option key={reason.id} value={reason.id}>{reason.name}</option>)}</select>{form.errors.motivo_objecion_id && <p className="mt-1 text-sm text-red-600">{form.errors.motivo_objecion_id}</p>}</div><div><label className="text-sm font-medium text-gray-700">Comentario</label><textarea rows="4" value={form.data.comentario_objecion} onChange={(e) => form.setData('comentario_objecion', e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 focus:border-red-500 focus:ring-red-500" placeholder="Explica qué debe corregirse" />{form.errors.comentario_objecion && <p className="mt-1 text-sm text-red-600">{form.errors.comentario_objecion}</p>}</div></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setObjecting(false)} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Cancelar</button><button disabled={form.processing} className="rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Registrar objeción</button></div></form></Modal>
            <Modal show={assigningResponsible} onClose={() => setAssigningResponsible(false)} maxWidth="lg"><form onSubmit={(event) => { event.preventDefault(); responsibleForm.post(route('purchase-invoice-approvals.assign-responsible', invoice.id), { preserveScroll: true, onSuccess: () => setAssigningResponsible(false) }); }} className="p-6"><h2 className="text-xl font-bold">Asignar responsable</h2><select value={responsibleForm.data.user_id} onChange={(e) => responsibleForm.setData('user_id', e.target.value)} className="mt-5 w-full rounded-lg border-gray-300"><option value="">Selecciona un usuario</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select>{responsibleForm.errors.user_id && <p className="mt-1 text-sm text-red-600">{responsibleForm.errors.user_id}</p>}<textarea rows="3" value={responsibleForm.data.comment} onChange={(e) => responsibleForm.setData('comment', e.target.value)} placeholder="Comentario opcional" className="mt-3 w-full rounded-lg border-gray-300" /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setAssigningResponsible(false)} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={responsibleForm.processing} className="rounded-lg bg-green-700 px-4 py-2 font-semibold text-white">Guardar</button></div></form></Modal>
            <Modal show={assigningPo} onClose={() => setAssigningPo(false)} maxWidth="lg"><form onSubmit={(event) => { event.preventDefault(); poForm.post(route('purchase-invoice-approvals.assign-po', invoice.id), { preserveScroll: true, onSuccess: () => setAssigningPo(false) }); }} className="p-6"><h2 className="text-xl font-bold">Asignar OC manual</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><input type="number" min="1" value={poForm.data.manual_oc_doc_num} onChange={(e) => poForm.setData('manual_oc_doc_num', e.target.value)} placeholder="Número OC" className="rounded-lg border-gray-300" /><input type="number" min="1" value={poForm.data.manual_oc_doc_entry} onChange={(e) => poForm.setData('manual_oc_doc_entry', e.target.value)} placeholder="DocEntry opcional" className="rounded-lg border-gray-300" /></div>{poForm.errors.manual_oc_doc_num && <p className="mt-1 text-sm text-red-600">{poForm.errors.manual_oc_doc_num}</p>}<textarea rows="3" value={poForm.data.comment} onChange={(e) => poForm.setData('comment', e.target.value)} placeholder="Comentario opcional" className="mt-3 w-full rounded-lg border-gray-300" /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setAssigningPo(false)} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={poForm.processing} className="rounded-lg bg-green-700 px-4 py-2 font-semibold text-white">Guardar</button></div></form></Modal>
            <Modal show={assigningSubstitute} onClose={() => setAssigningSubstitute(false)} maxWidth="lg"><form onSubmit={(event) => { event.preventDefault(); substituteForm.post(route('purchase-invoice-approvals.assign-substitute', invoice.id), { preserveScroll: true, onSuccess: () => setAssigningSubstitute(false) }); }} className="p-6"><h2 className="text-xl font-bold">Asignar suplente</h2><p className="mt-1 text-sm text-gray-500">El suplente reemplaza al responsable cuando este no está disponible. Recibirá la notificación de la factura.</p><select value={substituteForm.data.user_id} onChange={(e) => substituteForm.setData('user_id', e.target.value)} className="mt-5 w-full rounded-lg border-gray-300"><option value="">Selecciona un usuario</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select>{substituteForm.errors.user_id && <p className="mt-1 text-sm text-red-600">{substituteForm.errors.user_id}</p>}<textarea rows="3" value={substituteForm.data.comment} onChange={(e) => substituteForm.setData('comment', e.target.value)} placeholder="Comentario opcional (motivo de la suplencia)" className="mt-3 w-full rounded-lg border-gray-300" /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setAssigningSubstitute(false)} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={substituteForm.processing} className="rounded-lg bg-amber-700 px-4 py-2 font-semibold text-white">Guardar suplente</button></div></form></Modal>
            <Modal show={confirmingApproval} onClose={() => setConfirmingApproval(false)} maxWidth="lg"><form onSubmit={(event) => { event.preventDefault(); approve(); }} className="p-6"><h2 className="text-xl font-bold">Aprobar factura</h2><p className="mt-1 text-sm text-gray-500">¿Confirmas que la factura corresponde a lo solicitado? Puedes adjuntar un respaldo opcional (screenshot, PDF, etc.).</p><div className="mt-5"><label className="text-sm font-medium text-gray-700">Respaldos (opcional, máx. 5)</label><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,.gif" onChange={(e) => addAttachments(e.target.files)} className="mt-1 block w-full text-sm text-gray-500 file:mr-4 file:rounded-md file:border-0 file:bg-green-50 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-green-700 hover:file:bg-green-100" /><p className="mt-1 text-xs text-gray-400">PDF o imágenes, máximo 10 MB por archivo.</p>{approvalForm.data.attachments.length > 0 && <ul className="mt-3 divide-y divide-gray-100 rounded-lg border border-gray-200">{approvalForm.data.attachments.map((file, index) => <li key={`${file.name}-${index}`} className="flex items-center justify-between px-3 py-2 text-sm"><span className="truncate text-gray-700">{file.name}</span><button type="button" onClick={() => removeAttachment(index)} className="text-sm font-semibold text-red-600 hover:underline">Quitar</button></li>)}</ul>}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setConfirmingApproval(false)} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Cancelar</button><button disabled={approvalForm.processing} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Confirmar aprobación</button></div></form></Modal>
        </AuthenticatedLayout>
    );
}
