import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Modal from '@/Components/Modal';
import Pagination from '@/Components/PurchaseInvoices/Pagination';
import StatusBadge from '@/Components/PurchaseInvoices/StatusBadge';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';

const money = (value, currency = 'CLP') => new Intl.NumberFormat('es-CL', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value || 0);

export default function Unassigned({ invoices, users, filters, options }) {
    const empty = { proveedor: '', cuenta: '', area: '', especie: '' };
    const [filter, setFilter] = useState({ ...empty, ...filters });
    const [selected, setSelected] = useState(null);
    const [mode, setMode] = useState(null);
    const [userSearch, setUserSearch] = useState('');
    const responsible = useForm({ user_id: '', comment: '' });
    const purchaseOrder = useForm({ manual_oc_doc_num: '', manual_oc_doc_entry: '', comment: '' });
    const substitute = useForm({ user_id: '', comment: '' });
    const matchingUsers = useMemo(() => users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(userSearch.toLowerCase())), [users, userSearch]);
    const close = () => { setMode(null); setSelected(null); setUserSearch(''); responsible.reset(); purchaseOrder.reset(); substitute.reset(); };
    const open = (invoice, nextMode) => { setSelected(invoice); setMode(nextMode); };
    const applyFilters = (event) => { event.preventDefault(); router.get(route('purchase-invoice-approvals.unassigned'), filter, { preserveState: true, replace: true }); };

    return (
        <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800">Facturas sin asignar</h2>}>
            <Head title="Facturas sin asignar" />
            <div className="mx-auto max-w-[1500px] space-y-6 p-4 sm:p-6">
                <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-violet-700">Bandeja de Contabilidad</p><h1 className="mt-1 text-2xl font-bold text-gray-900">Facturas pendientes de asignación</h1><p className="mt-1 text-sm text-gray-500">Documentos recibidos desde SAP sin orden de compra y sin responsable.</p></div><span className="rounded-full bg-violet-100 px-4 py-2 text-sm font-bold text-violet-800">{invoices.total} pendientes</span></div>

                <form onSubmit={applyFilters} className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input value={filter.proveedor} onChange={(e) => setFilter({ ...filter, proveedor: e.target.value })} placeholder="Proveedor" className="rounded-lg border-gray-300 text-sm" /><input value={filter.cuenta} onChange={(e) => setFilter({ ...filter, cuenta: e.target.value })} placeholder="Código o nombre de cuenta" className="rounded-lg border-gray-300 text-sm" /><select value={filter.area} onChange={(e) => setFilter({ ...filter, area: e.target.value })} className="rounded-lg border-gray-300 text-sm"><option value="">Todas las áreas</option>{options.areas.map((item) => <option key={item.area} value={item.area}>{item.nombre_area || item.area}</option>)}</select><select value={filter.especie} onChange={(e) => setFilter({ ...filter, especie: e.target.value })} className="rounded-lg border-gray-300 text-sm"><option value="">Todas las especies</option>{options.species.map((item) => <option key={item.especie} value={item.especie}>{item.nombre_especie || item.especie}</option>)}</select></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => { setFilter(empty); router.get(route('purchase-invoice-approvals.unassigned')); }} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Limpiar</button><button className="rounded-lg bg-violet-700 px-5 py-2 text-sm font-semibold text-white">Filtrar</button></div></form>

                <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-4 py-3">Factura</th><th className="px-4 py-3">Proveedor / detalle</th><th className="px-4 py-3">Cuenta</th><th className="px-4 py-3">Monto</th><th className="px-4 py-3">Antigüedad</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Acciones</th></tr></thead><tbody className="divide-y divide-gray-100">{invoices.data.map((invoice) => <tr key={invoice.id} className="align-top hover:bg-gray-50"><td className="whitespace-nowrap px-4 py-4"><Link href={route('purchase-invoice-approvals.show', invoice.id)} className="font-bold text-green-700">{invoice.folio}</Link><div className="mt-1 text-xs text-gray-500">{invoice.invoice_date || 'Sin fecha'}</div></td><td className="max-w-sm px-4 py-4"><div className="font-semibold text-gray-900">{invoice.provider}</div><div className="mt-1 line-clamp-2 text-xs text-gray-500">{invoice.description || 'Sin descripción'}</div></td><td className="px-4 py-4 text-gray-600">{invoice.accounts.join(' · ') || 'Sin cuenta informada'}</td><td className="whitespace-nowrap px-4 py-4 font-semibold">{money(invoice.total, invoice.currency)}</td><td className={`whitespace-nowrap px-4 py-4 font-semibold ${invoice.age_hours >= 48 ? 'text-red-600' : 'text-amber-700'}`}>{invoice.age_hours < 24 ? `${invoice.age_hours} h` : `${Math.floor(invoice.age_hours / 24)} d`}</td><td className="px-4 py-4"><StatusBadge status={invoice.status} /></td><td className="px-4 py-4"><div className="flex min-w-36 flex-col gap-2"><button onClick={() => open(invoice, 'responsible')} className="rounded-lg bg-green-700 px-3 py-2 text-xs font-semibold text-white">Asignar responsable</button><button onClick={() => open(invoice, 'po')} className="rounded-lg border border-gray-300 px-3 py-2 text-xs font-semibold text-gray-700">Asignar OC</button><button onClick={() => open(invoice, 'substitute')} className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800">Asignar suplente</button></div></td></tr>)}</tbody></table></div>{invoices.data.length === 0 && <p className="p-10 text-center text-gray-500">No hay facturas pendientes de asignación.</p>}<Pagination links={invoices.links} /></div>
            </div>

            <Modal show={mode === 'responsible'} onClose={close} maxWidth="lg"><form onSubmit={(event) => { event.preventDefault(); responsible.post(route('purchase-invoice-approvals.assign-responsible', selected.id), { preserveScroll: true, onSuccess: close }); }} className="p-6"><h2 className="text-xl font-bold">Asignar responsable</h2><p className="mt-1 text-sm text-gray-500">Factura {selected?.folio} · {selected?.provider}</p><input value={userSearch} onChange={(e) => setUserSearch(e.target.value)} placeholder="Buscar por nombre o correo" className="mt-5 w-full rounded-lg border-gray-300 text-sm" /><select size="6" value={responsible.data.user_id} onChange={(e) => responsible.setData('user_id', e.target.value)} className="mt-2 w-full rounded-lg border-gray-300 text-sm">{matchingUsers.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select>{responsible.errors.user_id && <p className="mt-1 text-sm text-red-600">{responsible.errors.user_id}</p>}<textarea rows="3" value={responsible.data.comment} onChange={(e) => responsible.setData('comment', e.target.value)} placeholder="Comentario opcional" className="mt-3 w-full rounded-lg border-gray-300 text-sm" /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancelar</button><button disabled={responsible.processing} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Asignar y notificar</button></div></form></Modal>

            <Modal show={mode === 'po'} onClose={close} maxWidth="lg"><form onSubmit={(event) => { event.preventDefault(); purchaseOrder.post(route('purchase-invoice-approvals.assign-po', selected.id), { preserveScroll: true, onSuccess: close }); }} className="p-6"><h2 className="text-xl font-bold">Asignar orden de compra</h2><p className="mt-1 text-sm text-gray-500">La OC manual se conserva separada de la información SAP.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><input type="number" min="1" value={purchaseOrder.data.manual_oc_doc_num} onChange={(e) => purchaseOrder.setData('manual_oc_doc_num', e.target.value)} placeholder="Número de OC" className="rounded-lg border-gray-300 text-sm" /><input type="number" min="1" value={purchaseOrder.data.manual_oc_doc_entry} onChange={(e) => purchaseOrder.setData('manual_oc_doc_entry', e.target.value)} placeholder="DocEntry (opcional)" className="rounded-lg border-gray-300 text-sm" /></div>{purchaseOrder.errors.manual_oc_doc_num && <p className="mt-1 text-sm text-red-600">{purchaseOrder.errors.manual_oc_doc_num}</p>}<textarea rows="3" value={purchaseOrder.data.comment} onChange={(e) => purchaseOrder.setData('comment', e.target.value)} placeholder="Comentario opcional" className="mt-3 w-full rounded-lg border-gray-300 text-sm" /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancelar</button><button disabled={purchaseOrder.processing} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Guardar OC</button></div></form></Modal>

            <Modal show={mode === 'substitute'} onClose={close} maxWidth="lg"><form onSubmit={(event) => { event.preventDefault(); substitute.post(route('purchase-invoice-approvals.assign-substitute', selected.id), { preserveScroll: true, onSuccess: close }); }} className="p-6"><h2 className="text-xl font-bold">Asignar suplente</h2><p className="mt-1 text-sm text-gray-500">Factura {selected?.folio} · {selected?.provider}</p><input value={userSearch} onChange={(e) => setUserSearch(e.target.value)} placeholder="Buscar por nombre o correo" className="mt-5 w-full rounded-lg border-gray-300 text-sm" /><select size="6" value={substitute.data.user_id} onChange={(e) => substitute.setData('user_id', e.target.value)} className="mt-2 w-full rounded-lg border-gray-300 text-sm">{matchingUsers.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select>{substitute.errors.user_id && <p className="mt-1 text-sm text-red-600">{substitute.errors.user_id}</p>}<textarea rows="3" value={substitute.data.comment} onChange={(e) => substitute.setData('comment', e.target.value)} placeholder="Comentario opcional (motivo de la suplencia)" className="mt-3 w-full rounded-lg border-gray-300 text-sm" /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancelar</button><button disabled={substitute.processing} className="rounded-lg bg-amber-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Guardar suplente</button></div></form></Modal>
        </AuthenticatedLayout>
    );
}
