import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

function ReasonRow({ reason }) {
    const [data, setData] = useState({ name: reason.name, active: reason.active, sort_order: reason.sort_order });
    const save = () => router.put(route('purchase-invoice-objection-reasons.update', reason.id), data, { preserveScroll: true });
    return <tr className="border-b border-gray-100"><td className="px-4 py-3"><input value={data.name} onChange={(e) => setData({ ...data, name: e.target.value })} className="w-full rounded-lg border-gray-300 text-sm" /></td><td className="px-4 py-3"><input type="number" min="0" value={data.sort_order} onChange={(e) => setData({ ...data, sort_order: Number(e.target.value) })} className="w-24 rounded-lg border-gray-300 text-sm" /></td><td className="px-4 py-3"><label className="inline-flex items-center gap-2 text-sm"><input type="checkbox" checked={data.active} onChange={(e) => setData({ ...data, active: e.target.checked })} className="rounded border-gray-300 text-green-600" />Activo</label></td><td className="px-4 py-3 text-right"><button onClick={save} className="rounded-lg border border-green-700 px-3 py-2 text-sm font-semibold text-green-700">Guardar</button></td></tr>;
}

export default function ObjectionReasons({ reasons }) {
    const form = useForm({ name: '', active: true, sort_order: reasons.length + 1 });
    const submit = (e) => { e.preventDefault(); form.post(route('purchase-invoice-objection-reasons.store'), { preserveScroll: true, onSuccess: () => form.reset('name') }); };
    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800">Configuración · Motivos de objeción</h2>}><Head title="Motivos de objeción" /><div className="mx-auto max-w-4xl space-y-5 p-4 sm:p-6"><div><h1 className="text-2xl font-bold text-gray-900">Motivos de objeción</h1><p className="mt-1 text-sm text-gray-500">Desactivar conserva el historial y lo quita de futuras decisiones.</p></div><form onSubmit={submit} className="grid gap-3 rounded-xl border border-gray-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_110px_auto]"><div><input value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} placeholder="Nuevo motivo" className="w-full rounded-lg border-gray-300" />{form.errors.name && <p className="mt-1 text-sm text-red-600">{form.errors.name}</p>}</div><input type="number" min="0" value={form.data.sort_order} onChange={(e) => form.setData('sort_order', Number(e.target.value))} className="rounded-lg border-gray-300" aria-label="Orden" /><button disabled={form.processing} className="rounded-lg bg-green-700 px-4 py-2 font-semibold text-white">Agregar</button></form><div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><table className="min-w-full"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Motivo</th><th className="px-4 py-3">Orden</th><th className="px-4 py-3">Estado</th><th></th></tr></thead><tbody>{reasons.map((reason) => <ReasonRow key={reason.id} reason={reason} />)}</tbody></table></div></div></AuthenticatedLayout>;
}
