import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router } from '@inertiajs/react';
import { useState } from 'react';

function OwnerRow({ owner, users }) {
    const [userId, setUserId] = useState(owner.user_id || '');
    const [active, setActive] = useState(owner.active);
    const [saving, setSaving] = useState(false);
    const save = () => { setSaving(true); router.post(route('sap-owner-users.store'), { owner_code: owner.owner_code, user_id: userId || null, active }, { preserveScroll: true, onFinish: () => setSaving(false) }); };
    return <tr className="border-b border-gray-100"><td className="px-4 py-4 font-mono font-bold text-gray-900">{owner.owner_code}</td><td className="px-4 py-4 text-sm text-gray-600">{owner.invoice_count}</td><td className="px-4 py-4"><select value={userId} onChange={(e) => setUserId(e.target.value)} className="w-full min-w-56 rounded-lg border-gray-300 text-sm"><option value="">Sin usuario asociado</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select></td><td className="px-4 py-4"><label className="inline-flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={(e) => setActive(e.target.checked)} className="rounded border-gray-300 text-green-600 focus:ring-green-500" />Activo</label></td><td className="px-4 py-4">{owner.unmapped ? <span className="rounded-full bg-orange-100 px-2 py-1 text-xs font-semibold text-orange-800">Sin homologar</span> : <span className="rounded-full bg-green-100 px-2 py-1 text-xs font-semibold text-green-800">Homologado</span>}</td><td className="px-4 py-4 text-right"><button onClick={save} disabled={saving} className="rounded-lg bg-green-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Guardando…' : 'Guardar'}</button></td></tr>;
}

export default function Owners({ owners, users, filters }) {
    const [search, setSearch] = useState(filters.buscar || '');
    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-gray-800">Configuración · Responsables SAP</h2>}><Head title="Responsables SAP" /><div className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6"><div><h1 className="text-2xl font-bold text-gray-900">OwnerCode SAP → Usuario intranet</h1><p className="mt-1 text-sm text-gray-500">Los OwnerCode detectados aparecen aunque todavía no tengan homologación.</p></div><form onSubmit={(e) => { e.preventDefault(); router.get(route('sap-owner-users.index'), { buscar: search }, { preserveState: true }); }} className="flex gap-2"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar OwnerCode" className="w-full max-w-sm rounded-lg border-gray-300" /><button className="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white">Buscar</button></form><div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">OwnerCode</th><th className="px-4 py-3">Facturas</th><th className="px-4 py-3">Usuario</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Validación</th><th></th></tr></thead><tbody>{owners.map((owner) => <OwnerRow key={owner.owner_code} owner={owner} users={users} />)}</tbody></table></div>{owners.length === 0 && <p className="p-10 text-center text-gray-500">No se han recibido OwnerCode desde SAP.</p>}</div></div></AuthenticatedLayout>;
}
